# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CFF_Fovea.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1024, 612)
        Form.setStyleSheet("background-color:black;\n"
"color:white;")
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1031, 41))
        self.frame.setStyleSheet("background-color:#1f2836;\n"
"color:white")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 0, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(930, 0, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(0, 10, 44, 23))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/newPrefix/Vekaria Healthcare Logo/VHC Logo.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(0, 40, 1021, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 150, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet(" QPushButton {\n"
"                background-color: black;\n"
"                color: white;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 210, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet(" QPushButton {\n"
"                background-color: white;\n"
"                color: black;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 270, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet(" QPushButton {\n"
"                background-color: black;\n"
"                color: white;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 330, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet(" QPushButton {\n"
"                background-color: black;\n"
"                color: white;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 390, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet(" QPushButton {\n"
"                background-color: black;\n"
"                color: white;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 450, 240, 40))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet(" QPushButton {\n"
"                background-color: black;\n"
"                color: white;\n"
"                border: none;\n"
"                border:2px solid white;\n"
"            }\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(280, 110, 711, 441))
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color:#1f2836;\n"
"border-radius:30px;\n"
"\n"
"\n"
"};\n"
"color:white;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.data2 = QtWidgets.QLabel(self.frame_5)
        self.data2.setGeometry(QtCore.QRect(580, 30, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(26)
        self.data2.setFont(font)
        self.data2.setStyleSheet("QLabel {\n"
"    background-color: black; /* Set background color to white */\n"
"    border: 2px solid Black; /* Set a solid red border with a width of 30 pixels */\n"
"    color:white;\n"
"}")
        self.data2.setAlignment(QtCore.Qt.AlignCenter)
        self.data2.setObjectName("data2")
        self.final_data = QtWidgets.QTextEdit(self.frame_5)
        self.final_data.setGeometry(QtCore.QRect(580, 100, 111, 281))
        self.final_data.setStyleSheet("QTextEdit {\n"
"    background-color: black; /* Set background color to white */\n"
"    border: 2px solid Black; /* Set a solid red border with a width of 30 pixels */\n"
"    color:brown;\n"
"    border-radius:0px;\n"
"}")
        self.final_data.setObjectName("final_data")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setGeometry(QtCore.QRect(170, 10, 291, 126))
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"border-radius:15px;\n"
"border:3px solid grey;\n"
"background-color:black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.data1 = QtWidgets.QLabel(self.frame_2)
        self.data1.setGeometry(QtCore.QRect(40, 60, 211, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(28)
        self.data1.setFont(font)
        self.data1.setStyleSheet("border:none;")
        self.data1.setAlignment(QtCore.Qt.AlignCenter)
        self.data1.setObjectName("data1")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 271, 50))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(22)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border:none;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setGeometry(QtCore.QRect(0, 170, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica Neue")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setGeometry(QtCore.QRect(50, 230, 134, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"    font-family: Arial;\n"
"\n"
"\n"
"    color: #4CAF50;\n"
"    background-color: #1a472a;\n"
"    border: 2px solid transparent;\n"
"    border-top: 2px solid #2d8549;\n"
"    border-left: 2px solid #2d8549;\n"
"    border-bottom: 2px solid #0d2415;\n"
"    border-right: 2px solid #0d2415;\n"
"    qproperty-alignment: AlignCenter;\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4),\n"
"                inset 1px 1px 2px rgba(255, 255, 255, 0.1);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #2a5a3a;\n"
"    border-top: 2px solid #0d2415;\n"
"    border-left: 2px solid #0d2415;\n"
"    border-bottom: 2px solid #2d8549;\n"
"    border-right: 2px solid #2d8549;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_3.setGeometry(QtCore.QRect(50, 340, 134, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    padding: 5px;\n"
"    color: #ff4444;\n"
"    padding: 5px;\n"
"    font-family: Arial;\n"
"    font-size:14px;\n"
"    background-color: #4d1f1f;\n"
"    border: 2px solid transparent;\n"
"    border-top: 2px solid #a33636;\n"
"    border-left: 2px solid #a33636;\n"
"    border-bottom: 2px solid #2b1111;\n"
"    border-right: 2px solid #2b1111;\n"
"    qproperty-alignment: AlignCenter;\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4),\n"
"                inset 1px 1px 2px rgba(255, 255, 255, 0.1);\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_2.setGeometry(QtCore.QRect(53, 284, 134, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    border-radius: 5px;\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    padding: 5px;\n"
"    font-family: Arial;\n"
"\n"
"\n"
" color: #FFA500;\n"
"    background-color: #4d3319;\n"
"    border: 2px solid transparent;\n"
"    border-top: 2px solid #b36b1b;\n"
"    border-left: 2px solid #b36b1b;\n"
"    border-bottom: 2px solid #2b1d0e;\n"
"    border-right: 2px solid #2b1d0e;\n"
"    qproperty-alignment: AlignCenter;\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.4),\n"
"                inset 1px 1px 2px rgba(255, 255, 255, 0.1);\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Next = QtWidgets.QPushButton(self.frame_5)
        self.Next.setGeometry(QtCore.QRect(440, 380, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Next.setFont(font)
        self.Next.setStyleSheet("\n"
"    QPushButton {\n"
"        background-color: transparent;\n"
"        color: white;\n"
"        border: 1px solid white;\n"
"        padding: 10px 20px;\n"
"        font-size: 24px;\n"
"        border-radius: 1px;\n"
"        font-weight: bold;\n"
"        transition: all 0.3s;\n"
"        margin: 2px;\n"
"        /* Add subtle initial shadow */\n"
"        border-bottom: 1px solid white;\n"
"        border-right: 1px solid white;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: rgba(33, 150, 243, 0.1);\n"
"        border: 2px solid #64B5F6;\n"
"        color: #64B5F6;\n"
"        /* Enhanced hover effect */\n"
"        border-bottom: 4px solid #42A5F5;\n"
"        border-right: 3px solid #42A5F5;\n"
"        margin: 2px;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(33, 150, 243, 0.2);\n"
"        border: 2px solid white;\n"
"        /* Create pressed effect */\n"
"        border-bottom: 2px solid white;\n"
"        border-right: 2px solid white;\n"
"        margin-top: 4px;\n"
"        margin-left: 2px;\n"
"        padding-top: 11px;\n"
"        padding-left: 21px;\n"
"    }\n"
"    \n"
"    QPushButton:disabled {\n"
"        background-color: transparent;\n"
"        color: #B0B0B0;\n"
"        border: 2px solid #B0B0B0;\n"
"        border-bottom: 4px solid #909090;\n"
"        border-right: 3px solid #909090;\n"
"    }\n"
"")
        self.Next.setObjectName("Next")
        self.Home = QtWidgets.QPushButton(self.frame_5)
        self.Home.setGeometry(QtCore.QRect(300, 380, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Home.setFont(font)
        self.Home.setStyleSheet("\n"
"    QPushButton {\n"
"        background-color: transparent;\n"
"        color: white;\n"
"        border: 1px solid white;\n"
"        padding: 10px 20px;\n"
"        font-size: 24px;\n"
"        border-radius: 1px;\n"
"        font-weight: bold;\n"
"        transition: all 0.3s;\n"
"        margin: 2px;\n"
"        /* Add subtle initial shadow */\n"
"        border-bottom: 1px solid white;\n"
"        border-right: 1px solid white;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: rgba(33, 150, 243, 0.1);\n"
"        border: 2px solid #64B5F6;\n"
"        color: #64B5F6;\n"
"        /* Enhanced hover effect */\n"
"        border-bottom: 4px solid #42A5F5;\n"
"        border-right: 3px solid #42A5F5;\n"
"        margin: 2px;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: rgba(33, 150, 243, 0.2);\n"
"        border: 2px solid white;\n"
"        /* Create pressed effect */\n"
"        border-bottom: 2px solid white;\n"
"        border-right: 2px solid white;\n"
"        margin-top: 4px;\n"
"        margin-left: 2px;\n"
"        padding-top: 11px;\n"
"        padding-left: 21px;\n"
"    }\n"
"    \n"
"    QPushButton:disabled {\n"
"        background-color: transparent;\n"
"        color: #B0B0B0;\n"
"        border: 2px solid #B0B0B0;\n"
"        border-bottom: 4px solid #909090;\n"
"        border-right: 3px solid #909090;\n"
"    }\n"
"")
        self.Home.setObjectName("Home")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Vekaria Healthcare"))
        self.label_3.setText(_translate("Form", "V1.0"))
        self.label_4.setText(_translate("Form", "Macular Densitometer                                                          CFF Fovea Test"))
        self.pushButton_4.setText(_translate("Form", "Flicker Demo"))
        self.pushButton_6.setText(_translate("Form", "CFF Fovea"))
        self.pushButton_7.setText(_translate("Form", "BRK Fovea"))
        self.pushButton_8.setText(_translate("Form", "CFF Para-Fovea"))
        self.pushButton_9.setText(_translate("Form", "BRK Para-Fovea"))
        self.pushButton_10.setText(_translate("Form", "Test Result"))
        self.data2.setText(_translate("Form", "24.5"))
        self.final_data.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">25.6</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">25.6</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">25.6</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">25.6</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:22pt;\">25.6</span></p></body></html>"))
        self.data1.setText(_translate("Form", "23.5"))
        self.label_6.setText(_translate("Form", "CFF Fovea"))
        self.label.setText(_translate("Form", "Test Status"))
        self.pushButton.setText(_translate("Form", "Machine Ready"))
        self.pushButton_3.setText(_translate("Form", "Flicker Visible"))
        self.pushButton_2.setText(_translate("Form", "Flicker Start"))
        self.Next.setText(_translate("Form", "Next"))
        self.Home.setText(_translate("Form", "Home"))
import vekarialogo_rc
import wifi_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
